"""empty message

Revision ID: a28fff3c6d05
Revises: 
Create Date: 2025-10-15 16:54:27.535732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a28fff3c6d05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('nome_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokendata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('momento_abertura', sa.DateTime(), nullable=False),
    sa.Column('momento_fechamento', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade',
    sa.Column('id_level', sa.Integer(), nullable=False),
    sa.Column('id_token', sa.Integer(), nullable=False),
    sa.Column('atividade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_level'], ['level.id'], ),
    sa.ForeignKeyConstraint(['id_token'], ['tokendata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividade')
    op.drop_table('tokendata')
    op.drop_table('level')
    # ### end Alembic commands ###
